steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/tiny-dancer-backend:$COMMIT_SHA',
        '-f',
        'backend.Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tiny-dancer-backend:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/tiny-dancer-frontend:$COMMIT_SHA',
        '-f',
        'frontend.Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tiny-dancer-frontend:$COMMIT_SHA']
